### ISSUE TITLE
Power Point

### ISSUE THREAD

**Issue by gommzystudio** [jonaboecker/ubiquitous-computing#2]
Wann machen wir die Power Point?

**Comment by jonaboecker** [comment]
Hab eine Präsentation basierend auf meinem Bericht im Drive erstellt und auch meinen Bericht hochgeladen. Ich würde vorschlagen, wir erstellen noch eine Folie mit den Problemen aus Lab1 und lesen ansonsten einfach nur den Bericht vor...

**Comment by jonaboecker** [comment]
Folgende Aufteilung würde ich vorschlagen:

1. Probleme Lab1 -> @jonaboecker 
2. Aufgaben 1-3 -> @TobiasReyEye 
3. Aufgaben 4-5 -> @gommzystudio
